apiVersion: apps/v1
kind: Deployment
metadata:
  name: sum-deployment
  labels:
    app: sum
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sum
  template:
    metadata:
      labels:
        app: sum
    spec:
      containers:
      - name: sumserver
        image: clrmbxs/sum
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      nodeSelector: 
        PoP: space_1

---
apiVersion: v1
kind: Service
metadata:
  name: sum-service
spec:
  selector:
    app: sum
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 31001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-deployment
  labels:
    app: sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sub
  template:
    metadata:
      labels:
        app: sub
    spec:
      containers:
      - name: subserver
        image: clrmbxs/sub
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      nodeSelector: 
        PoP: space_1

---
apiVersion: v1
kind: Service
metadata:
  name: sub-service
spec:
  selector:
    app: sub
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 31002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mul-deployment
  labels:
    app: mul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mul
  template:
    metadata:
      labels:
        app: mul
    spec:
      containers:
      - name: mulserver
        image: clrmbxs/mul
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      nodeSelector: 
        PoP: space_1

---
apiVersion: v1
kind: Service
metadata:
  name: mul-service
spec:
  selector:
    app: mul
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 31003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: div-deployment
  labels:
    app: div
spec:
  replicas: 1
  selector:
    matchLabels:
      app: div
  template:
    metadata:
      labels:
        app: div
    spec:
      containers:
      - name: divserver
        image: clrmbxs/div
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      nodeSelector: 
        PoP: space_1

---
apiVersion: v1
kind: Service
metadata:
  name: div-service
spec:
  selector:
    app: div
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 31004

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  labels:
    app: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculatorserver
        image: clrmbxs/calculator
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      nodeSelector: 
        PoP: space_1

---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 31000
    
